[build]
  command = "CI= npm run build"
  publish = "build"

[build.environment]
  REACT_APP_USE_MOCK_DATA = "true"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
